2016-08-25 18:29:52 Warning: Warning (2): Invalid argument supplied for foreach() in [C:\xampp\htdocs\note_taker\src\Template\Objects\add.ctp, line 6]
Request URL: /note_taker/objects/add
Referer URL: http://127.0.0.1/note_taker/
Client IP: 127.0.0.1
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 146
include - APP/Template\Objects\add.ctp, line 6
Cake\View\View::_evaluate() - CORE\src\View\View.php, line 1005
Cake\View\View::_render() - CORE\src\View\View.php, line 964
Cake\View\View::render() - CORE\src\View\View.php, line 588
Cake\Controller\Controller::render() - CORE\src\Controller\Controller.php, line 617
Cake\Http\ActionDispatcher::_invoke() - CORE\src\Http\ActionDispatcher.php, line 130
Cake\Http\ActionDispatcher::dispatch() - CORE\src\Http\ActionDispatcher.php, line 98
Cake\Http\BaseApplication::__invoke() - CORE\src\Http\BaseApplication.php, line 83
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Routing\Middleware\RoutingMiddleware::__invoke() - CORE\src\Routing\Middleware\RoutingMiddleware.php, line 52
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Routing\Middleware\AssetMiddleware::__invoke() - CORE\src\Routing\Middleware\AssetMiddleware.php, line 88
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Error\Middleware\ErrorHandlerMiddleware::__invoke() - CORE\src\Error\Middleware\ErrorHandlerMiddleware.php, line 51
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Http\Runner::run() - CORE\src\Http\Runner.php, line 51
Cake\Http\Server::run() - CORE\src\Http\Server.php, line 82
[main] - ROOT\webroot\index.php, line 37



2016-08-25 19:34:58 Warning: Warning (2): require_once(C:\xampp\htdocs\note_takervendor\paolo\cakephp\Validator.php): failed to open stream: No such file or directory in [C:\xampp\htdocs\note_taker\src\Controller\ObjectsController.php, line 14]
Request URL: /note_taker/objects/add
Referer URL: http://127.0.0.1/note_taker/objects/add
Client IP: 127.0.0.1
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 146
require_once - APP/Controller\ObjectsController.php, line 14
include - APP/Controller\ObjectsController.php, line 14
Composer\Autoload\includeFile - ROOT\vendor\composer\ClassLoader.php, line 412
Composer\Autoload\ClassLoader::loadClass() - ROOT\vendor\composer\ClassLoader.php, line 301
spl_autoload_call - [internal], line ??
class_exists - [internal], line ??
Cake\Core\App::_classExistsInBase() - CORE\src\Core\App.php, line 152
Cake\Core\App::className() - CORE\src\Core\App.php, line 64
Cake\Http\ControllerFactory::create() - CORE\src\Http\ControllerFactory.php, line 70
Cake\Http\ActionDispatcher::dispatch() - CORE\src\Http\ActionDispatcher.php, line 95
Cake\Http\BaseApplication::__invoke() - CORE\src\Http\BaseApplication.php, line 83
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Routing\Middleware\RoutingMiddleware::__invoke() - CORE\src\Routing\Middleware\RoutingMiddleware.php, line 52
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Routing\Middleware\AssetMiddleware::__invoke() - CORE\src\Routing\Middleware\AssetMiddleware.php, line 88
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Error\Middleware\ErrorHandlerMiddleware::__invoke() - CORE\src\Error\Middleware\ErrorHandlerMiddleware.php, line 51
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Http\Runner::run() - CORE\src\Http\Runner.php, line 51
Cake\Http\Server::run() - CORE\src\Http\Server.php, line 82
[main] - ROOT\webroot\index.php, line 37



2016-08-25 19:35:13 Error: Fatal Error (1): Class 'App\Controller\Validator' not found in [C:\xampp\htdocs\note_taker\src\Controller\ObjectsController.php, line 30]
Request URL: /note_taker/objects/add
Referer URL: http://127.0.0.1/note_taker/objects/add
Client IP: 127.0.0.1
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 216
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 98
[main] - [internal], line ??



2016-08-25 19:35:13 Error: [Cake\Error\FatalErrorException] Class 'App\Controller\Validator' not found
Request URL: /note_taker/objects/add
Referer URL: http://127.0.0.1/note_taker/objects/add
Client IP: 127.0.0.1
Stack Trace:
#0 C:\xampp\htdocs\note_taker\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(98): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Class 'App\\Cont...', 'C:\\xampp\\htdocs...', 30)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


